### ISSUE TITLE
to check bybit BTC volume (often it is the same as price)

### ISSUE THREAD

**Issue by ftso-eu** [mouradski/ftso-ws-prices#10]
As you can see, maybe bad data from bybit exchange

 {
      timestamp: '2023-08-02T11:04:38.979Z',
      price: 29535.58,
      **volume: 29535.58,**
      pair: 'USDC'
    }

**Comment by mouradski** [comment]
Thank you for reporting the bug, which exchange does it concern ?

**Comment by mouradski** [comment]
I'm not sure it's related but I just fixed trade amount for Bitrue 

https://github.com/mouradski/ftso-ws-prices/commit/99e067a259fd22de26b68597b70e0e1cba63b9ae

**Comment by LightFTSO** [comment]
This was fixed in #6
