### ISSUE TITLE
#15  check for message timeout only once after the last message was received

### ISSUE THREAD

**Issue by JamesGDiaz** [mouradski/ftso-ws-prices#16]
I realized that every time an exchange client connected, onOpen would schedule a new executor to check for message timeout, so I changed it (I think, again, Im no expert with Java) so that it would cancel the current scheduled task and then schedule a new one. This shouldn't leak threads

**Comment by mouradski** [comment]
https://github.com/mouradski/ftso-ws-prices/pull/15
